name: Track Overrides
description: Track Changes in Overrides Methods.
author: Francisco Roldan
inputs:
  github-token:
    description: "GitHub Token"
    required: true
branding:
  icon: alert-circle
  color: blue
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set base branch
      shell: bash
      run: echo "BASE_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV

    - name: Output
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })
    
    - name: Run override comparison
      shell: bash
      id: check_overrides
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          set -e 
          changed_methods=$(python ${{ github.action_path }}/src/track_overrides.py ${{ github.workspace }})
          echo "CHANGED_METHODS=$changed_methods" >> $GITHUB_ENV

          if [[ -n "$changed_methods" ]]; then
            echo "Override methods have changed in the upstream repository."
            echo "Changed methods: $changed_methods"

            # Post a comment on the PR
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
              -d "$(jq -nc --arg body "The following override methods have changed in the upstream repository:\n\n$changed_methods" '{body: $body}')"

            exit 1
          fi
    
    
    - name: Cleanup
      if: always()
      shell: bash
      run: |
        echo "Cleaning up any orphan processes..."
        pkill -f ${{ github.action_path }}/src/track_overrides.py || true

