name: Track Overrides

on:
  pull_request:

jobs:
  track_overrides:
    runs-on: ubuntu-latest
    name: Track Overrides
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:  Track Overrides
        uses: ./github-actions/track_overrides
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
